-- Migration: 2026-06-26_0012_asset_category_catalog.sql
-- Canonical inheritance-item catalog, stored as config in wrs_settings (not a new
-- table — read-mostly public config, no per-user data). `estate_path` is awareness-
-- only metadata (who claims and how), NEVER a share/division calculation (Cardinal #7).
-- Codes match the wrs_asset_category enum exactly so an asset's estate path is always
-- derived from its category via this catalog — no estate_path column on wrs_assets.
-- Idempotent upsert: re-running keeps a single row for this key.

insert into wrs_settings (key, value, description) values (
  'asset_category_catalog',
  $json$[
    {"code":"bank","group":"Keuangan digital","label_id":"Rekening bank & bank digital","label_en":"Bank & digital bank","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan dan diklaim lewat proses ahli waris di penyedia. Catat deposito (ada tanggal jatuh tempo) dan RDN bila terhubung ke sekuritas.","note_en":"Enters the estate; claimed via the provider's heir process. Note deposito maturity dates and any linked RDN."},
    {"code":"e_wallet","group":"Keuangan digital","label_id":"E-wallet & uang elektronik","label_en":"E-wallet / stored value","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan. Saldo sering tersebar di banyak aplikasi dan mudah terlewat — inti nilainya ada di panduan klaim.","note_en":"Enters the estate. Balances scatter across apps and are easily missed — the value is the claim guide."},
    {"code":"saham","group":"Keuangan digital","label_id":"Saham & sekuritas","label_en":"Brokerage / shares","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan; saham dan saldo RDN diklaim lewat proses ahli waris sekuritas. Catat email akun dan bank RDN.","note_en":"Enters the estate; shares and RDN cash claimed via the broker's heir process. Note account email and RDN bank."},
    {"code":"reksa_dana","group":"Keuangan digital","label_id":"Reksa dana","label_en":"Mutual funds","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan; unit dicairkan atau dialihkan lewat APERD.","note_en":"Enters the estate; units redeemed/transferred via the APERD."},
    {"code":"obligasi","group":"Keuangan digital","label_id":"SBN & obligasi","label_en":"Bonds","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan. Catat tanggal jatuh tempo dan kupon.","note_en":"Enters the estate. Note maturity and coupon dates."},
    {"code":"crypto","group":"Keuangan digital","label_id":"Aset kripto","label_en":"Crypto & digital assets","estate_path":"general","claim_routes":["R1","R3"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan. Untuk dompet self-custody, tanpa lokasi seed phrase/dompet aset bisa hilang permanen — catat di mana mencarinya, jangan pernah simpan kuncinya di sini.","note_en":"Enters the estate. For self-custody wallets, without the seed/wallet location the asset can be lost forever — record where to look, never the key itself."},
    {"code":"emas","group":"Keuangan digital","label_id":"Emas digital","label_en":"Digital gold","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan; ditebus atau dialihkan lewat proses ahli waris penyedia. Catat dalam gram.","note_en":"Enters the estate; redeemed via the provider's heir process. Record in grams."},
    {"code":"p2p","group":"Keuangan digital","label_id":"Pendanaan P2P","label_en":"P2P lending (lender)","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Posisi sebagai pemberi dana = piutang yang masuk harta peninggalan; platform membayarkan sisa pokok dan imbal hasil ke ahli waris.","note_en":"A lender position is a receivable in the estate; the platform pays remaining principal/returns to heirs."},
    {"code":"luar_negeri","group":"Keuangan digital","label_id":"Investasi luar negeri","label_en":"Foreign investments","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan, tetapi lintas yurisdiksi — penyedia luar negeri bisa minta dokumen hukum tersendiri dan prosesnya lebih lama.","note_en":"Enters the estate, but cross-jurisdiction — foreign providers may need separate legal documents and longer timelines."},
    {"code":"asuransi","group":"Proteksi & jaminan sosial","label_id":"Asuransi & takaful","label_en":"Insurance & takaful","estate_path":"bypass","claim_routes":["R2"],"surfaces_beneficiary_field":true,"note_id":"Uang pertanggungan umumnya dibayarkan langsung ke penerima manfaat yang terdaftar di polis, di luar pembagian waris umum. Bila belum ada penerima manfaat, manfaat dapat masuk ke harta peninggalan.","note_en":"The benefit is generally paid directly to the beneficiary named on the policy, outside the general estate split. If none is named, it may fall back into the estate."},
    {"code":"bpjs","group":"Proteksi & jaminan sosial","label_id":"BPJS & jaminan sosial","label_en":"BPJS / social security","estate_path":"bypass","claim_routes":["R2"],"surfaces_beneficiary_field":true,"note_id":"Manfaat (JHT, JKM, JP) umumnya dibayarkan ke ahli waris terdaftar sesuai aturan program, di luar pembagian waris umum. Sering tidak diklaim karena keluarga tidak tahu. BPJS Kesehatan bukan aset; tutup keanggotaan.","note_en":"Benefits (JHT, JKM, JP) are generally paid to the registered heir per scheme rules, outside the general estate split. Often unclaimed because the family doesn't know. BPJS Kesehatan is not an asset; close the membership."},
    {"code":"pensiun","group":"Proteksi & jaminan sosial","label_id":"Dana pensiun","label_en":"Pension (DPLK/Taspen/Asabri)","estate_path":"bypass","claim_routes":["R2"],"surfaces_beneficiary_field":true,"note_id":"Manfaat dibayarkan ke penerima atau ahli waris terdaftar sesuai aturan program (DPLK/Taspen/Asabri), di luar pembagian waris umum.","note_en":"Paid to the registered beneficiary per scheme rules (DPLK/Taspen/Asabri), outside the general estate split."},
    {"code":"bisnis","group":"Bisnis & kreatif digital","label_id":"Bisnis & penghasilan digital","label_en":"Online business / income","estate_path":"general","claim_routes":["R1","R4"],"surfaces_beneficiary_field":false,"note_id":"Saldo payout dan bisnisnya masuk harta peninggalan; penghasilan tetap mengalir setelah meninggal. Ketentuan platform kadang membatasi pengalihan.","note_en":"Payout balances and the business enter the estate; income keeps arriving after death. Platform terms may limit transfer."},
    {"code":"domain","group":"Bisnis & kreatif digital","label_id":"Domain & website","label_en":"Domains & sites","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan; dialihkan lewat registrar. Bisa hangus bila perpanjangan tidak dibayar — catat tanggal perpanjangan.","note_en":"Enters the estate; transferred via the registrar. Lapses if renewal is unpaid — note the renewal date."},
    {"code":"ip","group":"Bisnis & kreatif digital","label_id":"Kekayaan intelektual & royalti","label_en":"IP & royalties","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Hak kekayaan intelektual masuk harta peninggalan; aliran royalti berlanjut ke ahli waris selama masa berlaku hak cipta.","note_en":"Intellectual property enters the estate; royalty streams continue to heirs for the copyright term."},
    {"code":"poin","group":"Bisnis & kreatif digital","label_id":"Poin & loyalitas","label_en":"Points / miles","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Bila bisa dialihkan, masuk harta peninggalan; sering tidak bisa dialihkan atau hangus saat meninggal — catat dengan ekspektasi wajar.","note_en":"If transferable, enters the estate; often non-transferable or extinguished on death — record with realistic expectations."},
    {"code":"game","group":"Bisnis & kreatif digital","label_id":"Akun game & item virtual","label_en":"Gaming assets","estate_path":"general","claim_routes":["R3","R4"],"surfaces_beneficiary_field":false,"note_id":"Item bernilai jual masuk harta peninggalan bila bisa dialihkan; akses terkait login. Ketentuan platform sering melarang pengalihan.","note_en":"Resale-value items enter the estate where transferable; access is login-tied. Platform terms often forbid transfer."},
    {"code":"properti","group":"Fisik & dokumen","label_id":"Properti & kendaraan","label_en":"Property & vehicles","estate_path":"general","claim_routes":["R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan; balik nama lewat BPN/Samsat + notaris. Catat nomor sertifikat dan lokasi dokumen aslinya.","note_en":"Enters the estate; title transfer via BPN/Samsat + notaris. Note certificate number and where the original is stored."},
    {"code":"fisik","group":"Fisik & dokumen","label_id":"Barang berharga fisik","label_en":"Physical valuables","estate_path":"general","claim_routes":["R3","R1"],"surfaces_beneficiary_field":false,"note_id":"Masuk harta peninggalan; berbasis penguasaan fisik (atau proses ahli waris bank untuk SDB). Catat di mana barang/dokumen disimpan — jangan simpan kuncinya di sini.","note_en":"Enters the estate; possession-based (or the bank heir process for a safe deposit box). Note where items/documents are kept — never the key itself."},
    {"code":"utang","group":"Utang & liabilitas","label_id":"Utang & liabilitas","label_en":"Liabilities","estate_path":"liability","claim_routes":[],"surfaces_beneficiary_field":false,"note_id":"Bukan aset — kewajiban yang mengurangi harta peninggalan dan diselesaikan sebelum pembagian. Dicatat dan dijumlahkan terpisah dari aset. Sebagian bisa lunas otomatis (mis. KPR dengan asuransi jiwa kredit).","note_en":"Not an asset — an obligation that reduces the estate, settled before division. Listed and totaled separately. Some self-settle (e.g. KPR with credit-life insurance)."}
  ]$json$::jsonb,
  'Canonical 20-item inheritance category catalog (estate_path = awareness-only metadata; codes match wrs_asset_category)'
)
on conflict (key) do update set value = excluded.value, description = excluded.description;
